mono:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Hip_R
    pid: {p: 1600.0, i: 0.0, d: 8}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Thigh_R
    pid: {p: 1600.0, i: 0.0, d: 1}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Tibia_R
    pid: {p: 4000.0, i: 0, d: 1}
    
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: Ankle_R
    pid: {p: 500, i: 0, d: .1}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: Hip_Left
    pid: {p: 1600.0, i: 0.0, d: 8}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: Thigh_L
    pid: {p: 3000.0, i: 0.01, d: 1}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: Tibia_L
    pid: {p: 700.0, i: 0, d: 1}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: Ankle_L
    pid: {p: 500, i: 0, d: 1}

